/* Database */
DROP DATABASE IF EXISTS WUZU;
CREATE DATABASE WUZU;

--DROP DATABASE IF EXISTS WUZU_TEST;
--CREATE DATABASE WUZU_TEST;

/* Table */
DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(20) NOT NULL
  
  , IS_OPENED BOOLEAN DEFAULT 0 /* TINYINT(1) */
  
  , PRIMARY KEY (ID)
);

/* CRUD */
SELECT * FROM MENU;

INSERT INTO MENU (NAME, IS_OPENED) VALUES 
('file 1', 0),
('file 2', 0),
('folder 1', 1),
('file 3', 0),
('folder 2', 0)
;



COMMIT;