/* Database */
DROP DATABASE IF EXISTS WUZU;
CREATE DATABASE WUZU;

--DROP DATABASE IF EXISTS WUZU_TEST;
--CREATE DATABASE WUZU_TEST;

/* Table */
DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(20) NOT NULL
  , TYPE CHAR(1) NOT NULL /* R(oot), B(ranch), L(eaf) */
  , PARENT_ID INT NOT NULL
  
  , IS_OPENED BOOLEAN DEFAULT 0 /* TINYINT(1) */
  
  , PRIMARY KEY (ID)
);

/* Initail data */
INSERT INTO MENU (NAME, TYPE, PARENT_ID) VALUES
('문서', 'R', 0)
;

/* CRUD */
SELECT * FROM MENU;

COMMIT;