/* Database */
DROP DATABASE IF EXISTS WUZU_HOME;
CREATE DATABASE WUZU_HOME;

/* Table */
DROP TABLE IF EXISTS MENU;

CREATE TABLE MENU (
    ID INT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(20) NOT NULL
  , TYPE CHAR(1) NOT NULL /* R(oot), B(ranch), L(eaf) */
  , PARENT_ID INT NOT NULL
  , DEPTH TINYINT NOT NULL
  , ORDER_IN_DEPTH SMALLINT NOT NULL
  , URI VARCHAR(20) NOT NULL
  
  , IS_OPENED BOOLEAN DEFAULT 0 /* TINYINT(1) */
  
  , PRIMARY KEY (ID)
);